// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6f6R4YJxV_KizP8I0bEiR2t84O1j-gBA',
    appId: '1:162833217391:web:797aa1a701af19c1531a9a',
    messagingSenderId: '162833217391',
    projectId: 'bij-theke-bhat',
    authDomain: 'bij-theke-bhat.firebaseapp.com',
    storageBucket: 'bij-theke-bhat.firebasestorage.app',
    measurementId: 'G-VSRXTZ6DS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaF8nu_euWap1xIUIkS4xwFaMcCKxhdLM',
    appId: '1:162833217391:android:e3738c4507f16a1e531a9a',
    messagingSenderId: '162833217391',
    projectId: 'bij-theke-bhat',
    storageBucket: 'bij-theke-bhat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtw5O9D2m0nUV0VX24RHDFKed-LYbRjc8',
    appId: '1:162833217391:ios:b762d4407e38bce3531a9a',
    messagingSenderId: '162833217391',
    projectId: 'bij-theke-bhat',
    storageBucket: 'bij-theke-bhat.firebasestorage.app',
    iosBundleId: 'com.sit.bijThekeBhat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtw5O9D2m0nUV0VX24RHDFKed-LYbRjc8',
    appId: '1:162833217391:ios:b762d4407e38bce3531a9a',
    messagingSenderId: '162833217391',
    projectId: 'bij-theke-bhat',
    storageBucket: 'bij-theke-bhat.firebasestorage.app',
    iosBundleId: 'com.sit.bijThekeBhat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6f6R4YJxV_KizP8I0bEiR2t84O1j-gBA',
    appId: '1:162833217391:web:72b604fe15308102531a9a',
    messagingSenderId: '162833217391',
    projectId: 'bij-theke-bhat',
    authDomain: 'bij-theke-bhat.firebaseapp.com',
    storageBucket: 'bij-theke-bhat.firebasestorage.app',
    measurementId: 'G-JJ8MCCESS2',
  );
}
